LinkedtvhbbtvApplication.who=WHO
LinkedtvhbbtvApplication.what=WHAT
LinkedtvhbbtvApplication.where=WHERE
LinkedtvhbbtvApplication.chapter=CHAPTER
LinkedtvhbbtvApplication.bookmark=BOOKMARK
LinkedtvhbbtvApplication.shared=SHARED
LinkedtvhbbtvApplication.joined=JOINED
LinkedtvhbbtvApplication.time=TIME
LinkedtvhbbtvApplication.findOutMore=FIND OUT MORE
LinkedtvhbbtvApplication.rotateScreen=Rotate your screen to read more